# Generated by Django 2.1.7 on 2021-01-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=50)),
                ('video_file', models.FileField(default='', upload_to='videostream/video')),
            ],
        ),
    ]
